local M = {}

---@param colors table
---@param config table
function M.get_groups(colors, config)
  local c = colors
  local ui = c.ui
  local comment = { fg = ui.dim, italic = config.italic_comments }
  local string = { fg = c.foreground, italic = config.italic_strings }
  local keyword = { fg = c.foreground, bold = config.bold_keywords }
  local reverse = { fg = ui.bg, bg = c.foreground }

  return {
    Normal = { fg = ui.fg, bg = ui.bg },
    NormalFloat = { fg = ui.fg, bg = ui.float },
    NormalNC = { fg = ui.fg, bg = ui.bg },
    FloatBorder = { fg = ui.border },
    FloatTitle = { fg = ui.fg, bold = true },
    ColorColumn = { bg = ui.line },
    Cursor = { fg = ui.bg, bg = c.cursor },
    lCursor = { link = 'Cursor' },
    CursorColumn = { bg = ui.line },
    CursorLine = { bg = ui.line },
    CursorLineNr = { fg = ui.fg, bg = ui.line, bold = true },
    LineNr = { fg = ui.dim },
    LineNrAbove = { fg = ui.dim },
    LineNrBelow = { fg = ui.dim },
    SignColumn = { bg = ui.bg },
    Folded = { fg = ui.dim, bg = ui.line },
    FoldColumn = { fg = ui.dim, bg = ui.bg },

    Directory = { fg = ui.fg, bold = true },
    EndOfBuffer = { fg = ui.dim },
    NonText = { fg = ui.dim },
    SpecialKey = { fg = ui.dim },
    Whitespace = { fg = ui.dim },
    Conceal = { fg = ui.dim },
    Title = { fg = ui.fg, bold = true },

    Visual = { bg = ui.selection },
    VisualNOS = { link = 'Visual' },
    Search = reverse,
    IncSearch = { fg = ui.bg, bg = ui.fg, bold = true },
    CurSearch = { link = 'IncSearch' },
    Substitute = reverse,
    MatchParen = { fg = ui.fg, bg = ui.selection, bold = true },

    StatusLine = { fg = ui.fg, bg = ui.line },
    StatusLineNC = { fg = ui.dim, bg = ui.line },
    WinBar = { fg = ui.fg, bg = ui.line, bold = true },
    WinBarNC = { fg = ui.dim, bg = ui.line },
    TabLine = { fg = ui.dim, bg = ui.line },
    TabLineFill = { fg = ui.dim, bg = ui.line },
    TabLineSel = { fg = ui.fg, bg = ui.bg, bold = true },
    WinSeparator = { fg = ui.border, bg = ui.bg },
    VertSplit = { link = 'WinSeparator' },

    Pmenu = { fg = ui.fg, bg = ui.line },
    PmenuSel = reverse,
    PmenuSbar = { bg = ui.line },
    PmenuThumb = { bg = ui.fg },
    PmenuExtra = { fg = ui.dim },
    WildMenu = reverse,

    Question = { fg = ui.fg, bold = true },
    MoreMsg = { fg = ui.fg },
    ModeMsg = { fg = ui.fg },
    ErrorMsg = { fg = ui.fg, bg = ui.line, bold = true },
    WarningMsg = { fg = ui.fg, bold = true },
    QuickFixLineNr = { fg = ui.dim },
    qfLineNr = { fg = ui.dim },
    qfFileName = { fg = ui.fg, bold = true },

    Comment = comment,
    Todo = { fg = ui.fg, bg = ui.line, bold = true },
    Identifier = { fg = ui.fg },
    Function = { fg = ui.fg, bold = true },
    Statement = keyword,
    Conditional = keyword,
    Repeat = keyword,
    Label = keyword,
    Operator = { fg = ui.fg },
    Keyword = keyword,
    Exception = keyword,
    PreProc = { fg = ui.fg, bold = true },
    Include = { fg = ui.fg, bold = true },
    Define = { fg = ui.fg, bold = true },
    Macro = { fg = ui.fg, bold = true },
    PreCondit = keyword,
    Type = { fg = ui.fg, underline = true },
    StorageClass = keyword,
    Structure = { fg = ui.fg, underline = true },
    Typedef = { fg = ui.fg, underline = true },
    Special = { fg = ui.fg, bold = true },
    SpecialChar = { fg = ui.fg, bold = true },
    Tag = { fg = ui.fg, bold = true },
    Delimiter = { fg = ui.fg },
    SpecialComment = { fg = ui.dim, italic = true },
    Debug = { fg = ui.fg, bold = true },
    Underlined = { fg = ui.fg, underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { fg = ui.dim },
    Error = reverse,
    String = string,
    Character = string,
    Number = { fg = ui.fg, bold = true },
    Boolean = { fg = ui.fg, bold = true },
    Float = { fg = ui.fg, bold = true },
    Constant = { fg = ui.fg, bold = true },

    DiffAdd = { bg = ui.line },
    DiffChange = { bg = ui.selection },
    DiffDelete = { fg = ui.dim, bg = ui.line, strikethrough = true },
    DiffText = { bg = ui.selection, bold = true },
    DiffAdded = { fg = ui.fg, bold = true },
    DiffRemoved = { fg = ui.dim, strikethrough = true },
    DiffChanged = { fg = ui.fg, underline = true },

    Added = { fg = ui.fg, bold = true },
    Removed = { fg = ui.dim, strikethrough = true },
    Changed = { fg = ui.fg, underline = true },

    DiagnosticError = { fg = ui.fg, bold = true },
    DiagnosticWarn = { fg = ui.fg, underline = true },
    DiagnosticInfo = { fg = ui.fg, italic = true },
    DiagnosticHint = { fg = ui.dim, italic = true },
    DiagnosticUnderlineError = { sp = ui.fg, undercurl = true, bold = true },
    DiagnosticUnderlineWarn = { sp = ui.fg, underline = true },
    DiagnosticUnderlineInfo = { sp = ui.fg, undercurl = true },
    DiagnosticUnderlineHint = { sp = ui.dim, undercurl = true },
    DiagnosticVirtualTextError = { fg = ui.dim, bold = true },
    DiagnosticVirtualTextWarn = { fg = ui.dim, underline = true },
    DiagnosticVirtualTextInfo = { fg = ui.dim, italic = true },
    DiagnosticVirtualTextHint = { fg = ui.dim, italic = true },

    ['@comment'] = comment,
    ['@comment.documentation'] = comment,
    ['@comment.todo'] = { fg = ui.fg, bg = ui.line, bold = true },
    ['@string'] = string,
    ['@string.escape'] = { fg = ui.fg, bold = true },
    ['@string.special'] = { fg = ui.fg, bold = true },
    ['@character'] = string,
    ['@number'] = { fg = ui.fg, bold = true },
    ['@boolean'] = { fg = ui.fg, bold = true },
    ['@float'] = { fg = ui.fg, bold = true },
    ['@keyword'] = keyword,
    ['@keyword.function'] = keyword,
    ['@keyword.operator'] = keyword,
    ['@keyword.return'] = keyword,
    ['@keyword.import'] = keyword,
    ['@keyword.exception'] = keyword,
    ['@keyword.conditional'] = keyword,
    ['@keyword.repeat'] = keyword,
    ['@keyword.storage'] = keyword,
    ['@keyword.directive'] = keyword,
    ['@keyword.directive.define'] = keyword,
    ['@label'] = keyword,
    ['@operator'] = { fg = ui.fg },
    ['@function'] = { fg = ui.fg, bold = true },
    ['@function.builtin'] = { fg = ui.fg, bold = true },
    ['@function.call'] = { fg = ui.fg, bold = true },
    ['@function.macro'] = { fg = ui.fg, bold = true },
    ['@function.method'] = { fg = ui.fg, bold = true },
    ['@method'] = { fg = ui.fg, bold = true },
    ['@constructor'] = { fg = ui.fg, bold = true },
    ['@type'] = { fg = ui.fg, underline = true },
    ['@type.builtin'] = { fg = ui.fg, underline = true },
    ['@type.definition'] = { fg = ui.fg, underline = true },
    ['@type.qualifier'] = keyword,
    ['@module'] = { fg = ui.fg, bold = true },
    ['@namespace'] = { fg = ui.fg, bold = true },
    ['@variable'] = { fg = ui.fg },
    ['@variable.builtin'] = { fg = ui.fg, bold = true },
    ['@variable.member'] = { fg = ui.fg },
    ['@variable.parameter'] = { fg = ui.fg, italic = true },
    ['@constant'] = { fg = ui.fg, bold = true },
    ['@constant.builtin'] = { fg = ui.fg, bold = true },
    ['@constant.macro'] = { fg = ui.fg, bold = true },
    ['@property'] = { fg = ui.fg },
    ['@field'] = { fg = ui.fg },
    ['@parameter'] = { fg = ui.fg, italic = true },
    ['@punctuation.delimiter'] = { fg = ui.fg },
    ['@punctuation.bracket'] = { fg = ui.fg },
    ['@punctuation.special'] = { fg = ui.fg, bold = true },
    ['@tag'] = { fg = ui.fg, bold = true },
    ['@tag.attribute'] = { fg = ui.fg },
    ['@tag.delimiter'] = { fg = ui.dim },
    ['@markup.heading'] = { fg = ui.fg, bold = true },
    ['@markup.bold'] = { bold = true },
    ['@markup.italic'] = { italic = true },
    ['@markup.underline'] = { underline = true },
    ['@markup.strikethrough'] = { strikethrough = true },
    ['@markup.link'] = { fg = ui.fg, underline = true },
    ['@markup.link.url'] = { fg = ui.fg, underline = true },
    ['@markup.link.label'] = { fg = ui.fg, bold = true },
    ['@markup.raw'] = { fg = ui.fg, bg = ui.line },
    ['@markup.list'] = { fg = ui.fg },
    ['@markup.quote'] = { fg = ui.dim, italic = true },

    GitSignsAdd = { fg = ui.fg, bold = true },
    GitSignsChange = { fg = ui.fg, underline = true },
    GitSignsDelete = { fg = ui.dim, strikethrough = true },
    GitSignsUntracked = { fg = ui.dim },

    TelescopeNormal = { fg = ui.fg, bg = ui.bg },
    TelescopeBorder = { fg = ui.border, bg = ui.bg },
    TelescopePromptNormal = { fg = ui.fg, bg = ui.line },
    TelescopePromptBorder = { fg = ui.border, bg = ui.line },
    TelescopePromptTitle = { fg = ui.bg, bg = ui.fg, bold = true },
    TelescopeResultsTitle = { fg = ui.fg, bold = true },
    TelescopePreviewTitle = { fg = ui.fg, bold = true },
    TelescopeSelection = reverse,
    TelescopeMatching = { fg = ui.fg, bold = true },

    CmpItemAbbrMatch = { fg = ui.fg, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = ui.fg, bold = true },
    CmpItemKind = { fg = ui.dim },
    CmpItemMenu = comment,
    BlinkCmpLabelMatch = { fg = ui.fg, bold = true },
    BlinkCmpMenuSelection = reverse,

    NeoTreeNormal = { fg = ui.fg, bg = ui.bg },
    NeoTreeDirectoryName = { fg = ui.fg, bold = true },
    NeoTreeDirectoryIcon = { fg = ui.fg },
    NeoTreeFileName = { fg = ui.fg },
    NeoTreeFileIcon = { fg = ui.dim },
    NeoTreeModifiedFile = { fg = ui.fg, bold = true },
    NeoTreeGitModified = { fg = ui.fg, underline = true },
    NeoTreeGitAdded = { fg = ui.fg, bold = true },
    NeoTreeGitDeleted = { fg = ui.dim, strikethrough = true },
    NeoTreeGitIgnored = { fg = ui.dim },

    NvimTreeFolderName = { fg = ui.fg, bold = true },
    NvimTreeFolderIcon = { fg = ui.fg },
    NvimTreeOpenedFolderName = { fg = ui.fg, bold = true },
    NvimTreeRootFolder = { fg = ui.fg, bold = true },
    NvimTreeGitDirty = { fg = ui.fg, underline = true },
    NvimTreeGitNew = { fg = ui.fg, bold = true },
    NvimTreeGitDeleted = { fg = ui.dim, strikethrough = true },

    WhichKey = { fg = ui.fg },
    WhichKeyGroup = { fg = ui.fg, bold = true },
    WhichKeyDesc = { fg = ui.dim },
    WhichKeySeparator = { fg = ui.dim },

    MiniStatuslineModeNormal = reverse,
    MiniStatuslineModeInsert = reverse,
    MiniStatuslineModeVisual = reverse,
    MiniStatuslineModeReplace = reverse,
    MiniStatuslineModeCommand = reverse,
    MiniStatuslineModeOther = reverse,
  }
end

return M
